### PR TITLE
WIP: read_AdcSums_with_zero_suppression_modes_1_and_2

### PR DESCRIPTION
**Pull request by dneise**
related to #144

### CODE REVIEW

**Comment by MaxNoe** [comment]
I think using nan for the missing pixels would be much clearer

**Comment by dneise** [comment]
Note: force pushed to rebase to current master

**Comment by dneise** [comment]
The was an error in the ordering of the pixels of zero supressed ADCSamples objects which was solved in e333bc9. 

I think a similar error might still be in ADCSums ...

and tests are still needed to verify all what I claim here.

**Comment by dneise** [comment]
Okay nice .. it works on linux but not yet on osx .. something with my wget is wrong ... tomorrow I'll try with curl.

**Comment by dneise** [comment]
Finally..

So here are two tests, showing the two new features:
https://github.com/cta-observatory/pyeventio/blob/f2bbeee1110a4b743a6f12ca6a727726b87bb363/tests/simtel/test_zero_suppression.py

(skipped on OSX, due to problems downloading the test files from konrads home)

 - it uses pyhessio for testing the adc sums
 - it uses non-zero-suppresed files for testing the adc samples

**Comment by dneise** [comment]
very nice improvements @MaxNoe should be merge this now?

**Pull request merged**
