### PR TITLE
Implement PixelList v1, ImageParameters v6, read LaserCalibration n_pixels as unsigned

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Review by orelgueta — CHANGES_REQUESTED** [review]
Hi Max, you forgot to commit also the new test files, so the tests fail on GitHub. The changes to the code look good though, so once the files are uploaded and tests pass, I will approve.

**Comment by maxnoe** [comment]
> Hi Max, you forgot to commit also the new test files, so the tests fail on GitHub. 

I am waiting for a suitable file from @lheckmann, the original file she used for the report is a bit too large to use as a test file and since it only triggers with more than 37k pixels, I wasn't yet trying myself to create one.

**Comment by lheckmann** [comment]
> > Hi Max, you forgot to commit also the new test files, so the tests fail on GitHub.
> 
> I am waiting for a suitable file from @lheckmann, the original file she used for the report is a bit too large to use as a test file and since it only triggers with more than 37k pixels, I wasn't yet trying myself to create one.

I sent you one on slack that should work. But here it is as well, let me know if it works: 
[hess_raw.simtel.gz](https://github.com/cta-observatory/pyeventio/files/13307643/hess_raw.simtel.gz)

**Comment by maxnoe** [comment]
@orelgueta File added and tests adapted

**Review by orelgueta — APPROVED** [review]

**Pull request merged**
